trigger:
  - main

variables:
- name: var1
  value: var1-value
- name: var2
  value: var2-value
- name: env-var
  value: env-var-value
- name: notebook-workspace-path
  value: test_ado

stages:
  - stage: Stage1
    displayName: Stage 1
    jobs:
    - job: Job1
      displayName: Job 1
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
        - task: Bash@3
          displayName: "Test LS"
          inputs:
            targetType: 'inline'
            script: ls -l
        - task: Bash@3
          displayName: "Test PWD"
          inputs:
            targetType: 'inline'
            script: pwd
        - task: Bash@3
          displayName: "Deploy Databricks Notebook"
          inputs:
            filePath: test.sh
            arguments: $(variables['var1']) $(variables['var2'])
            workingDirectory: $(variables['notebook-workspace-path'])
          env:
            ENV_VAR_SECRET: $(variables['env-var'])
