trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  a: 'a'
  b_b: 'b_b'
  c-c: 'c-c'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      description: ${{ variables.a }}
      script: |
        echo ${{ variables.a }}
  - task: Bash@3
    inputs:
      targetType: 'inline'
      description: $(a)
      script: |
        echo $(a)