trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  a: 'a'
  b_b: 'b_b'
  c-c: 'c-c'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo $variables.a
        echo $variables.b_b
        echo $variables.c-c
        echo $(variables.c-c)
        echo ${variables.c-c}