trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: a
  value: a

steps:
  - task: Bash@3
    displayName: bash1
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ variables.a }}
  - task: Bash@3
    displayName: bash2
    inputs:
      targetType: 'inline'
      script: |
        echo $(a)
  - task: Bash@3
    displayName: bash3
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ variables['a'] }}